version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: itmochan-backend
    expose:
      - "8080"
    ports:
      - "8080:8080/tcp"
    networks:
      - itmochan-network
  postgres:
    container_name: postgres-container-itmochan
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres
    expose:
      - "5432"
    networks:
      - itmochan-network
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - itmochan-network

volumes:
  db-data:
    driver: local
    name: postgres-itmochan
  s3-data:
    driver: local
    name: s3-itmochan

networks:
  itmochan-network:
    driver: bridge